spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProjetJava
    username: dbuser
    password: p455w0rd
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always